### ISSUE TITLE
Incorrect measurement values

### ISSUE THREAD

**Issue by ujjawalcse** [vcarlosrb/3d-body-measurements#2]
Hi @vcarlosrb ,
I'm getting incorrect measuremnts from the mesh.
Steps to generate my Apose model is:-
1. I have used your suggested repo to generate smpl model (https://github.com/gulvarol/smplpytorch)
2. I generated shape parameters from smplify-x repo results ('betas') (https://github.com/vchoutas/smplify-x)
3. Pose parameters is same as you suggested 
I can see the mesh is generated well in Apose.
 
Here is the code to generate my Apose body model:
`def create_Apose(parameters_filepath,gender,outfile):
    cuda = True
    batch_size = 1

    # Create the SMPL layer
    smpl_layer = SMPL_Layer(
        center_idx=0,
        gender=gender,
        model_root='/home/ujjawal/my_work/Fashion/3d-body-measurements/smplpytorch/smplpytorch/native/models')

    # Generate random pose and shape parameters
    #pose_params = torch.rand(batch_size, 72) * 0.2
    #shape_params = torch.rand(batch_size, 10) * 0.03
    pose_params=np.zeros(72,dtype='float32')
    pose_params[50],pose_params[53]=5.6,-5.6
    f=open(parameters_filepath,'rb')
    mydict=pickle.load(f)
    shape_params=mydict['betas'][0]
    #b=np.load(parameters_filepath)
    #shape_params=b['betas.npy']
    print('shape params:',shape_params)
    print(pose_params.shape)
    print(shape_params.shape)

    # GPU mode
    if cuda:
        pose_params = torch.from_numpy(pose_params.reshape(1,pose_params.shape[0])).cuda()
        shape_params = torch.from_numpy(shape_params.reshape(1,shape_params.shape[0])).cuda()
        smpl_layer.cuda()
    print(pose_params.shape)
    print(shape_params.shape)

    # Forward from the SMPL layer
    verts, Jtr = smpl_layer(pose_params.float(), th_betas=shape_params.float())
    mesh=trimesh.Trimesh(verts.cpu()[0],smpl_layer.th_faces.cpu())
    #trimesh.exchange.obj.export_obj(mesh)
    trimesh.exchange.export.export_mesh(mesh,outfile,file_type='obj')
    #mesh.show()`

Can you please suggest me any proper way to generate mesh for these measurements?

**Comment by vcarlosrb** [comment]
Hi @ujjawalcse ,

Could you share me the value of shape param?, I will try to replicate the problem to help you.

**Comment by vcarlosrb** [comment]
I have made a test based on the code you provide me

![libreria](https://user-images.githubusercontent.com/16088635/106846306-a1b57880-667a-11eb-9251-e46d18b043bb.png)

**Comment by ujjawalcse** [comment]
These are some shape parameters that i have generated and using here,
1. [-0.12551743 -0.08154773  0.46331197  0.37727806  0.07479186 -0.02540274
  -0.35916808  0.00177525  0.39542076 -0.24011266]

2. [-0.44749486  0.14630315  0.3330895  -0.01145098 -0.01371216 -0.01259378
  -0.5241899   0.07745483  0.48279464 -0.21152341]

3. [ 0.24685304  0.06949284  1.3396181   0.8778122   0.11858778 -0.21556161
  -0.8737918   0.04969895  0.6163808  -0.44504935]

4. [ 0.8973918   0.33662653 -0.72982025 -0.6947338  -0.00277401 -0.23435631
  -0.28436667  0.24465096  0.15873474  0.03615111]

5. [ 0.31639358  0.71688765 -0.37785295 -0.56469417 -0.14261815  0.07158425
  -0.58034414  0.06008048  0.64179724 -0.04585703]

I'm worrying that how to deal with that situation when the position of the camera or person is not fix.
I think there is no issue in measuring (means your code is fine), because you are feeding the generated mesh and calculating everything. So it totally depends on the generated mesh.
How to co-relate these measurements in real world?

**Comment by vcarlosrb** [comment]
Ohh, I think you mean that the person must be in the same pose that I indicate for the library to work correctly. To answer that, I tell you that a couple of months ago I was seeing a model that estimates the shape and pose of a person. The model worked as follows:

1. From an RGB image (a photo of the real world of a person) your mask is obtained.
2. From the mask obtained, a regressor model is entered to estimate the shape and pose parameters.
3. The estimated shape and pose parameters enter the SMPL model for mesh generation.

As I already estimate the shape of the person based on the RGB image (it can be any pose, it is an image of the real world). Then I modify the pose parameter so that the person is in 'pose A', and later use the library to obtain body measurements.

Use the STRAPS model to estimate the shape and pose of a person from an RGB image.
https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose

**Comment by ujjawalcse** [comment]
Hi @vcarlosrb,
Actually I was also executing the same repo yesterday only that you mentioned right now for shape and pose.
But when I added your package of body measurement, I was getting some error. No worry, I can resolve those error.
Your fork of the same repo already include some measurements right!. 
Initially I was generating mesh from real world image only using smplify that can generate both smpl and smplx model.
But the shape parameters is not generalizing for fat persons. That's why I want to use method that can generate real world shape parameters. Pose is not an issue for me.
So, I can see you have forked the STRAPS repo and added the code for body measurements in predict_3d.py.
can it give all measurements or only chest and waist?

Thanks a lot for your kind conversation.
I'll try to execute STRAPS repo right now for getting all the measurements.

**Comment by vcarlosrb** [comment]
Hi @ujjawalcse,

It is correct, based on the repository of the STARPS project, make some modifications to obtain body measurements. The library offers you the following measurements:
- Weight (kilos) (to be validated)
- Height (meters)
- Chest circumference (meters)
- Hip circumference (meters)
- Waist Circumference (meters)
- Thigh Circumference (meters)
- Outside leg length (meters)
- Inside leg length (meters)
- Length from neck to hip (meters)

By the way, the library has not been tested on tights with very extreme shapes, for example with people who are overweight.

On the other hand, to obtain the body measurements, Trimesh was used, which helped to section the mesh obtaining several horizontal cuts. Based on that, it was calculated approximately in which cut the circumference measurements are located, and by means of trimesh the perimeter of the cut was obtained. For length measurements, it is easier to calculate, which would be the number of cuts between a point A and a point B, and then multiply this quantity by the separation between cuts.

**Comment by ujjawalcse** [comment]
Thanks @vcarlosrb ,
Got completely.
