### ISSUE TITLE
How I can generate person.obj for my own image ??

### ISSUE THREAD

**Issue by 1zuu** [vcarlosrb/3d-body-measurements#3]

**Comment by vcarlosrb** [comment]
Hello Isuru,

For this context, the .obj file is not important. To the library works, it needs the vertices and faces. For my purpose, I use the SMPL model that provide me the vertices and faces of a person, then, to use in other situation, I can export these 2 values in a .obj file.

I can avoid use .obj file if I use the SMPL model and the library in the same project. If you can generate this values, I suggest you review the SMPL model or other models that can generate human shapes based on vertices and faces. 

https://smpl.is.tue.mpg.de/

**Comment by 1zuu** [comment]
Can you please tell me the exact way that I can create that object file from SMPL model. Thank you in advance.
