### ISSUE TITLE
the shoulder circumference is missing

### ISSUE THREAD

**Issue by Dreedzy** [vcarlosrb/3d-body-measurements#4]
Hello Carlos, thank you very much for the work you have done! Would it be possible to implement the shoulder circumference? Is it in your skills? 

Thank you very much!

![shoulders](https://user-images.githubusercontent.com/63453162/118184563-cc625a80-b43b-11eb-83e4-751c346eac94.jpg)

**Comment by vcarlosrb** [comment]
Hi Dreedzy, sorry for the delay in responding. I just updated the library with shoulder girth. Version 1.1.1 comes with that functionality.

**Comment by Dreedzy** [comment]
thanks a lot for this feature! your project is great, I'm just struggling to create a 3D model from photos, I tried to use the STRAPS library, as you already recommended, but without success ... even with an NVIDIA card on a linux distribution, impossible to make the libraries work properly. Is there any other way to do this that you know of?

**Comment by vcarlosrb** [comment]
I see.  I was using the STRAPS project as a base architecture to estimate 3D bodies from an RGB image, I raised it on a linux distro with a 4gb nvidia card.  You tell me what problems you have, I could help you.
