### ISSUE TITLE
How do i run this project?

### ISSUE THREAD

**Issue by cameronking4** [vcarlosrb/3d-body-measurements#5]
I ran pip install. Could you please let me know how to set up my environment to try testing this repo. I'd greatly appreciate it.
<img width="516" alt="Screen Shot 2021-05-27 at 5 20 08 PM" src="https://user-images.githubusercontent.com/35708477/119898399-a5555f80-bef6-11eb-8b86-5709df4c4dc2.png">

**Comment by vcarlosrb** [comment]
Hi cameronking4. If you want to test the library on your machine without installing the dependency via pip install, I recommend you follow the following steps:
1. Create a python environment: python -m venv ENV
2. Activate created environment: source ENV/bin/activate
3. Install the following dependencies: trimesh> = 3.8.8, numpy> = 1.19.1, scipy> = 1.5.2, shapely> = 1.7.1 and networkx> = 2.5
4. Run the example inside the example folder: python example.py

**Comment by julian-122** [comment]
> Hi cameronking4. If you want to test the library on your machine without installing the dependency via pip install, I recommend you follow the following steps:
> 
> 1. Create a python environment: python -m venv ENV
> 2. Activate created environment: source ENV/bin/activate
> 3. Install the following dependencies: trimesh> = 3.8.8, numpy> = 1.19.1, scipy> = 1.5.2, shapely> = 1.7.1 and networkx> = 2.5
> 4. Run the example inside the example folder: python example.py

I followed these steps but when I execute example.py, the terminal waits for a second and then nothing.
How do I see the output? What am I missing?  Where am I supposed to be looking?
