### ISSUE TITLE
Vertices and Faces ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [vcarlosrb/3d-body-measurements#6]
Hello, thank you for your amazing implementation 
Can you guide me how can i get vertices and faces for my custom images to use with this implementation ?
It would be great if you can provide a Google Colab Notebook Demo for this repo, it'll help everyone and it'll be much appreciated,

Thank you

**Comment by vcarlosrb** [comment]
Hi @Adeel-Intizar ,

Thanks for asking. The [SMPL](https://smpl.is.tue.mpg.de/) model receives as input the pose (θ) and shape (β) parameters and returns the vertices and faces. Now, to get the pose and shape parameters you must train a previous model. In my case, a few months ago, I was working on a project and I used the [STRAPS](https://github.com/akashsengupta1997/STRAPS-3DHumanShapePose) model as a base, the architecture is as follows:

<img width="591" alt="Screen Shot 2021-04-30 at 09 14 15" src="https://user-images.githubusercontent.com/16088635/116707800-b01ee200-a994-11eb-889d-b8d0f3dc4e0a.png">

To use the library you can be guided by this [example](https://github.com/vcarlosrb/3d-body-measurements/blob/main/example/example.py).

I hope I have helped.

**Comment by Adeel-Intizar** [comment]
Can you tell me where and how can i get a smpl model for my custom images, which can be used with this implementation?
