### ISSUE TITLE
 anthropometry

### ISSUE THREAD

**Issue by websocketing** [vcarlosrb/3d-body-measurements#9]
I'm glad to see this project. I wonder if this project supports anthropometry? I need to measure the human parts of the generated manikin. I hope I can get your reply and information.

**Comment by vcarlosrb** [comment]
Hi!, well, this project require a mesh file generated by SMPL model, that is an .obj file that contains vertices and faces. Another requirement is that the pose of the person model must be 'A' pose. If your generated mannequin is an .obj file and it is in pose 'A', it should obtain the anthropometric measurements described.
